#!/usr/bin/env python3.6
# coding=utf-8

import logging
logger = logging.getLogger(__name__)

import sys
import inspect

from gym.common.logs import Logs
from gym.common.cfg import Config
from gym.common.asyncs.app import App
from gym.agent.agent import Agent


class GymAgent(App):
    def __init__(self):
        App.__init__(self)
        self.cfg = Config()
        
    def logs(self, info):
        filename = "/tmp/gym-agent-" + str(info.get("id")) + ".log"
        Logs(filename, debug=info.get("debug"))

    def set_routes(self):
        self.route("POST", "/{identifier}", self.handle)

    def run(self, argv):
        info = self.cfg.get_config(argv)
        if info:
            self.logs(info)               
            self.handler = Agent(info, self.in_queue, self.out_queue)
            try:
                self.main(info.get("url"))
            except Exception as e:
                logger.error("Exception on main App: %s", e)
        else:
            print("Could not start Agent")
            return -1


if __name__ == '__main__':
    gym_agent = GymAgent()
    gym_agent.run(sys.argv[1:])